# Generated by Django 5.1.3 on 2024-11-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Linkedin_links', models.URLField(max_length=1000)),
                ('Line_links', models.URLField(max_length=1000)),
            ],
        ),
    ]
