# Generated by Django 5.1.1 on 2024-11-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='email',
            new_name='メールアドレス',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='short_description',
            new_name='出身地',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='city',
            new_name='学位',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='degree',
            new_name='所在地',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='designation',
            new_name='職種',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='discription',
            new_name='説明文',
        ),
        migrations.RemoveField(
            model_name='about',
            name='age',
        ),
        migrations.RemoveField(
            model_name='about',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='about',
            name='website_link',
        ),
        migrations.AddField(
            model_name='about',
            name='年齢',
            field=models.IntegerField(default=25),
        ),
    ]
