# Generated by Django 5.1.1 on 2024-11-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_email_about_メールアドレス_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('学士号メディアコミュニケーション学部情報文化学科', models.CharField(max_length=2000)),
                ('日本語学校', models.CharField(max_length=2000)),
            ],
        ),
    ]
